name: build and publish docker image
on:
  push:
    branches:
      - develop
      - master
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USER_NAME }}/mongodb:latest .
      - name: Publish image to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/mongodb:latest
